include: extract_gdt.yaml
dataset_path: "/data2/Users/clark/hadrian_vllm/data/hf_datasets/read_gdt_for_id_from_render-single_images-prompt6_claude_try-17-50-multiturn"
task: "extract_gdt_17_50__multiturn"